### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false

### content configuration ###
theme: jekyll-theme-minimal
title: ViewModel Composition
logo: assets/ServiceComposer.png